from .dataset_node import NODE_CLASS_MAPPINGS as DATASET_NODE_CLASS_MAPPINGS
from .dataset_node import NODE_DISPLAY_NAME_MAPPINGS as DATASET_NODE_DISPLAY_NAME_MAPPINGS
from .nodes_train import NODE_CLASS_MAPPINGS as TRAIN_NODE_CLASS_MAPPINGS
from .nodes_train import NODE_DISPLAY_NAME_MAPPINGS as TRAIN_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **TRAIN_NODE_CLASS_MAPPINGS,
    **DATASET_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TRAIN_NODE_DISPLAY_NAME_MAPPINGS,
    **DATASET_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
